cinema/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinema import settings

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie')),
    path('review/', include('review.urls', namespace='review')),
    path('accounts/', include('registration.backends.default.urls')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/urls.py
from django.urls import path

from movie.views import MovieTemplateView, MovieListView, TotalDetailView, SearchListView

app_name = 'movie'
urlpatterns = [
    path('', MovieTemplateView.as_view(), name='home'),
    path('catalog/<str:category>/', MovieListView.as_view(), name='catalog'),
    path('search-catalog/', SearchListView.as_view(), name='search-catalog'),
    path('catalog/<str:category>/<int:pk>/', TotalDetailView.as_view(), name='detail'),
]

templates/Layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600%7CUbuntu:300,400,500,700" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}">
    <link rel="stylesheet" href="{% static 'css/photoswipe.css' %}">
    <link rel="stylesheet" href="{% static 'css/default-skin.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- Favicons -->
    <link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icon/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icon/apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icon/apple-touch-icon-144x144.png' %}">

    <title>{% block title %}{% endblock %}</title>

</head>
<body class="body">

{% include 'Layout/header.html' %}
<form class="align-content-end">
    <div class="form-group">
        <label>Select Country</label><br>
        <div class="select-country" data-input-name="country2" data-selected-country="US">
        </div>
    </div>
</form>
{% block content %}

{% endblock %}

{% include 'Layout/footer.html' %}

<!-- JS -->
<script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
{#<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>#}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
<script src="{% static 'js/jquery.mCustomScrollbar.min.js' %}"></script>
<script src="{% static 'js/wNumb.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/plyr.min.js' %}"></script>
<script src="{% static 'js/jquery.morelines.min.js' %}"></script>
<script src="{% static 'js/photoswipe.min.js' %}"></script>
<script src="{% static 'js/photoswipe-ui-default.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block js %}

{% endblock %}
</body>

</html>

templates/Layout/footer.html
{% load static %}
<!-- footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <!-- footer list -->
            <div class="col-12 col-md-3">
                <h6 class="footer__title">Download Our App</h6>
                <ul class="footer__app">
                    <li><a href="#"><img src="{% static 'img/Download_on_the_App_Store_Badge.svg' %}" alt=""></a></li>
                    <li><a href="#"><img src="{% static 'img/google-play-badge.png' %}" alt=""></a></li>
                </ul>
            </div>
            <!-- end footer list -->

            <!-- footer list -->
            <div class="col-6 col-sm-4 col-md-3">
                <h6 class="footer__title">Resources</h6>
                <ul class="footer__list">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Pricing Plan</a></li>
                    <li><a href="#">Help</a></li>
                </ul>
            </div>
            <!-- end footer list -->

            <!-- footer list -->
            <div class="col-6 col-sm-4 col-md-3">
                <h6 class="footer__title">Legal</h6>
                <ul class="footer__list">
                    <li><a href="#">Terms of Use</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Security</a></li>
                </ul>
            </div>
            <!-- end footer list -->

            <!-- footer list -->
            <div class="col-12 col-sm-4 col-md-3">
                <h6 class="footer__title">Contact</h6>
                <ul class="footer__list">
                    <li><a href="tel:+18002345678">+1 (800) 234-5678</a></li>
                    <li><a href="mailto:support@moviego.com">support@flixgo.com</a></li>
                </ul>
                <ul class="footer__social">
                    <li class="facebook"><a href="#"><i class="icon ion-logo-facebook"></i></a></li>
                    <li class="instagram"><a href="#"><i class="icon ion-logo-instagram"></i></a></li>
                    <li class="twitter"><a href="#"><i class="icon ion-logo-twitter"></i></a></li>
                    <li class="vk"><a href="#"><i class="icon ion-logo-vk"></i></a></li>
                </ul>
            </div>
            <!-- end footer list -->

            <!-- footer copyright -->
            <div class="col-12">
                <div class="footer__copyright">
                    <small><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></small>

                    <ul>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <!-- end footer copyright -->
        </div>
    </div>
</footer>
<!-- end footer -->

templates/Layout/header.html
{% load static %}
{% load i18n %}
<!-- header -->
<header class="header">
    <div class="header__wrap">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="header__content">
                        <!-- header logo -->
                        <a href="{% url 'movie:home' %}" class="header__logo">
                            <img src="{% static 'img/logo.svg' %}" alt="">
                        </a>
                        <!-- end header logo -->

                        <!-- header nav -->
                        <ul class="header__nav">
                            <!-- dropdown -->
                            <li class="header__nav-item">
                                <a class="dropdown-toggle header__nav-link" href="{% url 'movie:home' %}">Home</a>
                            </li>
                            <!-- end dropdown -->
                            <!-- dropdown -->
                            <!-- end dropdown -->
                            <li class="header__nav-item">
                                <a class="header__nav-link"
                                   href="{% url 'movie:catalog' category='series' %}">{% trans 'TV Series' %}
                                </a>
                            </li>
                            <li class="header__nav-item">
                                <a class="header__nav-link"
                                   href="{% url 'movie:catalog' category='cartoon' %}">{% trans 'Cartoons' %}
                                </a>
                            </li>
                            <li class="header__nav-item">
                                <a class="header__nav-link"
                                   href="{% url 'movie:catalog' category='films' %}">{% trans 'Films' %}
                                </a>
                            </li>
                        </ul>
                        <!-- end header nav -->

                        <!-- header auth -->
                        <div class=" header__auth">
                            <button class="header__search-btn" type="button">
                                <i class="icon ion-ios-search"></i>
                            </button>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'auth_logout' %}" class="header__sign-in">
                                    <i class="icon ion-ios-log-in"></i>
                                    <span>logout</span>
                                </a>
                            {% else %}
                                <a href="{% url 'auth_login' %}" class="header__sign-in">
                                    <i class="icon ion-ios-log-in"></i>
                                    <span>sign in</span>
                                </a>
                            {% endif %}

                        </div>
                        <!-- end header auth -->
                        <!-- header menu btn -->
                        <button class="header__btn" type="button">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                        <!-- end header menu btn -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- header search -->
    <form action="" class="header__search" method="get">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="header__search-content">
                        <input type="text" name="q"
                               placeholder="Search for a movie, TV Series that you are looking for">
                        <button type="submit">search</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- end header search -->
</header>
<!-- end header -->

templates/Layout/paginator.html
<div class="col-12">
    {% if page_obj.has_other_pages %}
        <ul class="paginator">
            {% if page_obj.has_previous %}
                <li class="paginator__item paginator__item--prev">
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="icon ion-ios-arrow-back"></i></a>
                </li>
            {% endif %}
            {% for paginato in page_obj.paginator.page_range %}
                <li class="paginator__item paginator__item--{% if page_obj.number == paginato %}active{% endif %}"><a
                        href="?page={{ paginato }}">{{ paginato }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="paginator__item paginator__item--next">
                    <a href="?page={{ page_obj.next_page_number }}"><i class="icon ion-ios-arrow-forward"></i></a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</div>